# apiVersion: v1
# kind: Service
# metadata:
#   name: microbank-api-service
# spec:
#   selector:
#     app: microbank-api
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer