swagger: "2.0"
info:
  title: Micro Bank gRPC API
  description: A production-grade Go API that provides money transfer services between accounts of registered users
  version: "1.0"
  contact:
    name: Kizito
    url: https://github.com/Rexkizzy22/micro-bank/
    email: kizitoinegbenose@gmail.com
tags:
  - name: MicroBank
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/create_user:
    post:
      summary: Create a new user
      description: Use this to create a new user
      operationId: MicroBank_CreateUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbCreateUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/pbCreateUserRequest'
      tags:
        - MicroBank
  /v1/login_user:
    post:
      summary: Log new user
      description: Use this to log in an existing user and get access token and refresh token
      operationId: MicroBank_LoginUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbLoginUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/pbLoginUserRequest'
      tags:
        - MicroBank
  /v1/update_user:
    patch:
      summary: Update a new user
      description: Use this to update a new user
      operationId: MicroBank_UpdateUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbUpdateUserResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/pbUpdateUserRequest'
      tags:
        - MicroBank
  /v1/verify_email:
    post:
      summary: Verify new user
      description: Use this to verify email of a new user
      operationId: MicroBank_VerifyEmail
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/pbVerifyEmailResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/pbVerifyEmailRequest'
      tags:
        - MicroBank
definitions:
  pbCreateUserRequest:
    type: object
    properties:
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      username:
        type: string
  pbCreateUserResponse:
    type: object
    properties:
      user:
        $ref: '#/definitions/pbUser'
  pbLoginUserRequest:
    type: object
    properties:
      password:
        type: string
      username:
        type: string
  pbLoginUserResponse:
    type: object
    properties:
      accessToken:
        type: string
      accessTokenExpiresAt:
        type: string
        format: date-time
      refreshToken:
        type: string
      refreshTokenExpiresAt:
        type: string
        format: date-time
      sessionId:
        type: string
      user:
        $ref: '#/definitions/pbUser'
  pbUpdateUserRequest:
    type: object
    properties:
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      username:
        type: string
  pbUpdateUserResponse:
    type: object
    properties:
      user:
        $ref: '#/definitions/pbUser'
  pbUser:
    type: object
    properties:
      createdAt:
        type: string
        format: date-time
      email:
        type: string
      fullName:
        type: string
      passwordChangedAt:
        type: string
        format: date-time
      username:
        type: string
  pbVerifyEmailRequest:
    type: object
    properties:
      emailId:
        type: string
        format: int64
      secretCode:
        type: string
  pbVerifyEmailResponse:
    type: object
    properties:
      isVerified:
        type: boolean
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
      message:
        type: string
